allowCheckoutWithoutPayment: '1'
allowEmptyCartOnCheckout: '0'
allowPartialPaymentOnCheckout: '0'
autoSetCartShippingMethodOption: '1'
autoSetNewCartAddresses: '1'
autoSetPaymentSource: '0'
currency: USD
freeOrderPaymentStrategy: complete
handle: CraftDemoStore
minimumTotalPriceStrategy: default
name: 'Craft Demo Store'
orderReferenceFormat: '{{number[:7]}}'
primary: true
requireBillingAddressAtCheckout: '0'
requireShippingAddressAtCheckout: '0'
requireShippingMethodSelectionAtCheckout: '0'
sortOrder: 99
useBillingAddressForTax: '0'
validateOrganizationTaxIdAsVatId: '0'
