billingAddressCondition:
  class: craft\commerce\elements\conditions\addresses\GatewayAddressCondition
  elementType: null
  fieldContext: global
handle: testPayment
isFrontendEnabled: '1'
name: 'Test Payment Gateway'
orderCondition:
  class: craft\commerce\elements\conditions\orders\GatewayOrderCondition
  elementType: craft\commerce\elements\Order
  fieldContext: global
paymentType: purchase
shippingAddressCondition:
  class: craft\commerce\elements\conditions\addresses\GatewayAddressCondition
  elementType: null
  fieldContext: global
sortOrder: 99
type: craft\commerce\gateways\Dummy
