fieldLayouts:
  03916891-6725-4719-bfc1-cebf91fc8862:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-15T13:42:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 2d7e7e4e-2f01-4272-975a-df5693e7d7b5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f4b73ada-226c-4a6e-a7db-c537c53b6569
        userCondition: null
handle: blogTags
name: 'Blog Tags'
