color: null
description: null
fieldLayouts:
  fb0a5969-dd32-42ea-b488-06f70aa1280a:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:4e34e0f3-6668-4826-8d50-a7eed3c41357'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-15T15:14:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 667194c0-3370-4db6-8ad3-03adad68255b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T15:17:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 62e7804c-1235-42c8-89fd-8e626644bb04 # Project Images
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2024b4c2-b6a9-4568-8a71-00c64de2e442
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T15:17:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 358899c5-3ac8-4059-adfe-fc70eb3586f4 # Project Description
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5a13568-6421-4e4e-a12e-47f67e356178
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T15:17:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6c3b32b8-173d-4538-ba0d-3c2fc0aa055f # Price
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d68b672c-eec7-4e15-b07d-ca817d548768
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T15:17:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 904c72b8-6312-40bc-8d73-1c4617021b3e # Stock Status
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5eac8f6b-f199-4098-b58f-63e8c391d2ad
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T15:17:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6d6caae3-ad43-4f95-a380-46fd159932b4 # Product Features
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a13392b-8b39-4a34-808d-b31db8d387db
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T15:17:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 10a054b0-1199-4924-94b7-ab6d6a720ec2 #  Product Categories
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e34e0f3-6668-4826-8d50-a7eed3c41357
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7551c29c-65bf-4295-8f23-bea1ff7fdf9e
        userCondition: null
    thumbFieldKey: 'layoutElement:2024b4c2-b6a9-4568-8a71-00c64de2e442'
handle: product
hasTitleField: true
icon: null
name: Product
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
