altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  8d2b68f8-047b-4f96-bfa5-626944a631df:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-14T16:45:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 28e1ad8d-9fb1-4a53-9c6c-66625b5a018b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0166173c-00a4-44b2-84dc-d680a383eea3
        userCondition: null
fs: local
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
