columnSuffix: null
handle: accentColor
instructions: null
name: 'Accent Color'
searchable: false
settings:
  default: null
  palette: null
  setRandom: true
  useConfigFile: true
translationKeyFormat: null
translationMethod: none
type: percipiolondon\colourswatches\fields\ColourSwatches
