columnSuffix: null
handle: featuredPost
instructions: null
name: 'Featured Post'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
