columnSuffix: null
handle: price
instructions: null
name: Price
searchable: false
settings:
  currency: EUR
  defaultValue: null
  max: null
  min: 0
  showCurrency: true
  size: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Money
