columnSuffix: null
handle: readingTime
instructions: null
name: 'Reading Time'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 1
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  step: null
  suffix: min
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
