defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 51e28d9a-a601-4c86-bd63-c2be7880c88c # Blog
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  e0781df1-416c-47c6-bd9b-98bad82f27e9: # Craft Demo
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry
    uriFormat: 'blog/{slug}'
type: channel
