defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 83b1c30e-4310-4c1b-99a4-e7f505c1da6f # Portfolio
handle: portfolio
maxAuthors: 1
name: Portfolio
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  e0781df1-416c-47c6-bd9b-98bad82f27e9: # Craft Demo
    enabledByDefault: true
    hasUrls: true
    template: portfolio/_entry
    uriFormat: 'portfolio/{slug}'
type: channel
