defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 4b7ff6de-1a1b-4e55-a808-1bf9de9445f8 # Product
handle: products
maxAuthors: 1
name: Products
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  e0781df1-416c-47c6-bd9b-98bad82f27e9: # Craft Demo
    enabledByDefault: true
    hasUrls: true
    template: products/_entry
    uriFormat: 'products/{slug}'
type: channel
